openapi: 3.1.0
info:
  title: Polygon Analytics API
  version: 1.0.0
  description: Access real-time trade data, RSI, VWAP, and MACD analytics using the Polygon.io API.
servers:
  - url: https://your-deployed-url.onrender.com
paths:
  /trade-analytics/{ticker}:
    get:
      summary: Get trade analytics (RSI, VWAP, MACD)
      operationId: getTradeAnalytics
      parameters:
        - name: ticker
          in: path
          required: true
          schema:
            type: string
        - name: apiKey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trade analytics with technical indicators
